# Generated by Django 5.1.4 on 2024-12-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='created',
        ),
        migrations.AddField(
            model_name='item',
            name='password',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
